# Generated by Django 2.2 on 2020-04-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Record',
        ),
        migrations.AddField(
            model_name='todolist',
            name='is_done',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
