# Generated by Django 2.2 on 2020-04-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_auto_20200426_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
