# Generated by Django 2.2 on 2020-04-27 01:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_auto_20200426_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
