# Generated by Django 2.2 on 2020-04-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0004_auto_20200427_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='feed_back',
            field=models.TextField(default='finished'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todolist',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
