# Generated by Django 2.2 on 2020-03-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='total_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
