# Generated by Django 2.2 on 2020-03-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_total_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='abstract',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
