# Generated by Django 2.2 on 2020-03-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200316_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='article/%Y%m%d/'),
        ),
    ]
