# Generated by Django 2.2 on 2020-03-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blog_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='blog/%Y%m%d/'),
        ),
    ]
