# Generated by Django 2.2 on 2020-05-02 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200316_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='view_ip',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('user_ip', models.CharField(max_length=15)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Website_views',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('views', models.IntegerField()),
            ],
        ),
    ]
