# Generated by Django 2.2 on 2020-05-03 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_view_ip_website_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='view_ip_history',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('user_ip', models.CharField(max_length=15)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
