# Generated by Django 2.2 on 2020-07-13 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20200713_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='algorithm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog', to='blog.BlogAlgorithm'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='datastructrue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog', to='blog.BlogClassifyDataStructure'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='difficulty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog', to='blog.BlogDifficulty'),
        ),
    ]
